window.SENTENCES_AUDIO_MAP = {
  "Can you play the flute?": "assets/audios/tts/fish_q_0_9f7d7364.mp3",
  "Yes, I can.": "assets/audios/tts/fish_opt_3b925184.mp3",
  "No, I can't.": "assets/audios/tts/fish_opt_5617396f.mp3",
  "Yes, I lake.": "assets/audios/tts/fish_opt_52aaebda.mp3",
  "Can the boat float?": "assets/audios/tts/fish_q_1_61328ed6.mp3",
  "Yes, it can.": "assets/audios/tts/fish_opt_9635b401.mp3",
  "No, it can't.": "assets/audios/tts/fish_opt_9dcd6713.mp3",
  "No, it dive.": "assets/audios/tts/fish_opt_c6e2b2fd.mp3",
  "Which word begins with Ll?": "assets/audios/tts/fish_q_2_5fe40ee5.mp3",
  "leaf": "assets/audios/tts/fish_opt_bab4ff04.mp3",
  "nose": "assets/audios/tts/fish_opt_41d1de28.mp3",
  "yard": "assets/audios/tts/fish_opt_9a09d699.mp3",
  "Which word begins with Yy?": "assets/audios/tts/fish_q_3_9fec5234.mp3",
  "yellow": "assets/audios/tts/fish_opt_d487dd0b.mp3",
  "night": "assets/audios/tts/fish_opt_93a04b06.mp3",
  "Which word has long vowel a?": "assets/audios/tts/fish_q_4_0e47df79.mp3",
  "cake": "assets/audios/tts/fish_opt_a1b85851.mp3",
  "feet": "assets/audios/tts/fish_opt_e03f9063.mp3",
  "cube": "assets/audios/tts/fish_opt_18a64f72.mp3",
  "Which word has long vowel i?": "assets/audios/tts/fish_q_5_9eefc0e0.mp3",
  "bike": "assets/audios/tts/fish_opt_dde2c7ad.mp3",
  "boat": "assets/audios/tts/fish_opt_dd8fc45d.mp3",
  "green": "assets/audios/tts/fish_opt_9f274107.mp3"
};
